from . import fsm_order
from . import fsm_location
from . import res_partner
from . import sale_order
from . import fsm_equipment
from . import fsm_location_person
from . import product_template
from . import stock_move
from . import stock_picking
from . import package_lump
from . import fsm_stages
from . import fsm_stage_status
from . import notificator_configurator